/* Customer Review System - requires existing supabaseClient from supabase-config.js */
document.addEventListener("DOMContentLoaded",()=>{const modal=document.getElementById("review-modal"),openBtn=document.getElementById("open-review-btn"),closeBtn=document.getElementById("close-review-btn"),form=document.getElementById("review-form"),nameInput=document.getElementById("review-name"),textInput=document.getElementById("review-text"),ratingInput=document.getElementById("review-rating"),submitBtn=document.getElementById("submit-review-btn"),message=document.getElementById("review-message"),stars=document.querySelectorAll("#star-rating button"),list=document.getElementById("reviews-list"),avg=document.getElementById("average-rating"),avgStars=document.getElementById("average-stars"),count=document.getElementById("review-count");
if(!window.supabaseClient){console.error("supabaseClient was not found. Check supabase-config.js.");if(list)list.innerHTML='<p class="no-reviews">Review system is not connected.</p>';return}
function openModal(){modal.classList.add("active");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}
function closeModal(){modal.classList.remove("active");modal.setAttribute("aria-hidden","true");document.body.style.overflow=""}
openBtn?.addEventListener("click",openModal);closeBtn?.addEventListener("click",closeModal);modal?.addEventListener("click",e=>{if(e.target===modal)closeModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&modal.classList.contains("active"))closeModal()});
stars.forEach(star=>star.addEventListener("click",()=>{const rating=Number(star.dataset.rating);ratingInput.value=rating;stars.forEach(s=>s.classList.toggle("active",Number(s.dataset.rating)<=rating))}));
function escapeHTML(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}
function setMessage(t,err=false){message.textContent=t;message.style.color=err?"#d93025":"#16803c"}
function updateSummary(reviews){count.textContent=reviews.length;if(!reviews.length){avg.textContent="0.0";avgStars.textContent="☆☆☆☆☆";return}const total=reviews.reduce((s,r)=>s+Number(r.rating),0),a=total/reviews.length,r=Math.round(a);avg.textContent=a.toFixed(1);avgStars.textContent="★".repeat(r)+"☆".repeat(5-r)}
function renderReviews(reviews){if(!reviews.length){list.innerHTML='<div class="no-reviews"><p>No reviews yet.</p><p>Be the first customer to write a review!</p></div>';return}list.innerHTML=reviews.map(item=>{const rating=Number(item.rating),date=new Date(item.created_at).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"});return `<article class="review-card"><div class="review-card-header"><h3 class="review-card-name">${escapeHTML(item.name)}</h3><div class="review-card-stars">${"★".repeat(rating)+"☆".repeat(5-rating)}</div></div><p class="review-card-text">${escapeHTML(item.review)}</p><small class="review-card-date">${date}</small></article>`}).join("")}
async function loadReviews(){const{data,error}=await supabaseClient.from("reviews").select("id,name,rating,review,created_at").eq("status","approved").order("created_at",{ascending:false});if(error){console.error(error);list.innerHTML='<p class="no-reviews">Unable to load reviews.</p>';return}updateSummary(data||[]);renderReviews(data||[])}
form?.addEventListener("submit",async e=>{e.preventDefault();const name=nameInput.value.trim(),review=textInput.value.trim(),rating=Number(ratingInput.value);if(name.length<2)return setMessage("Please enter your name.",true);if(rating<1||rating>5)return setMessage("Please select a rating.",true);if(review.length<5)return setMessage("Please write a longer review.",true);submitBtn.disabled=true;submitBtn.textContent="Submitting...";const{error}=await supabaseClient.from("reviews").insert([{name,rating,review,status:"pending"}]);if(error){console.error(error);setMessage("Something went wrong. Please try again.",true)}else{setMessage("Thank you! Your review has been submitted and is waiting for approval.");form.reset();ratingInput.value=0;stars.forEach(s=>s.classList.remove("active"));setTimeout(()=>{closeModal();message.textContent=""},2500)}submitBtn.disabled=false;submitBtn.textContent="Submit Review"});loadReviews()});
